### PR TITLE
A cleaner way to install packages (experimental)

### PR DESCRIPTION
**Pull request by byronsharman**
**Main change not visible to the end user**
Instead of having a method for every package, I keep a list of package objects and have a single install method that functions with a few key pieces of information from each object.

**Changes to behavior**
While going through all the packages, I made some small standardizations (e.g. "Gnome" :arrow_right: "GNOME"). Additionally, clicking a button now prints the command that would be used to install the appropriate package. Assuming this branch stabilizes itself, the only change needed would be to swap `print` for `os.system`.

Some of the more customized methods were made generic again. These all have comments in `app_categories.py` and can be filtered with `grep '#' ignition/app_categories.py`:

```python3
        App("Chromium (apt)", "chromium-browser", "apt"), # already a transitional package to Snap
        App("Steam", "steam", "apt"), # used to be via Gdebi, is this a problem?
        App("VLC Media Player", "vlc", "apt"), # originally also was supposed to include DVD (.VOB) support
        App("VS Code", "code", "snap"), # Do we need a --classic here?
```

I have to figure out what's causing the merge conflict with this.

### CODE REVIEW

**Comment by joshlangley** [comment]
About the packages that you're unsure about:
| apt | snapd | .deb from websites | .AppImage |
| -- | -- | -- | -- |
| gnome-gmail | googletools-desktop | ulauncher | pling-store |
| sl (steamengine locomotive) | projectlibre | minecraft |  |
| gstreamer* | openoffice-desktopeditors | apacheopenoffice |  |
| aalib(-bin) |  |  |  |
| flashplayerstuff |  |  |  |
| ubuntustudio-installer |  |  |  |

Note that both .deb and .AppImage would be retrieved with wget and then operated on. I am considering using the snap minecraft-launcher-ot instead of Minecraft.deb

**Comment by joshlangley** [comment]
Also, Steam is not on apt, it is only from .deb at https://steamcdn-a.akamaihd.net/client/installer/steam.deb
(`wget https://steamcdn-a.akamaihd.net/client/installer/steam.deb && xdg-open steam.deb`)
Similarly, Minecraft is at `wget https://launcher.mojang.com/download/Minecraft.deb && xdg-open Minecraft.deb`

**Comment by joshlangley** [comment]
Also, some snaps need to be installed with --classic. Most IDEs won't install without it, and this is also true of other apps that are still being adjusted to snappy's sandboxing system. 
Some are:
`code, atom, codium, android-studio` there are others, but these are just common examples.

**Comment by joshlangley** [comment]
I also do want to keep the vlc DVD support, since that is a common reason people install vlc. Little things like this, or installing some good icon themes for LibreOffice, or later, I want to even be able to configure LibreOffice to have a more polished look on first startup, are the things I want to be in this app. It's designed to be an app for superusers and non-superusers alike, and must be able to 'just work' at all costs.
I know some of these things present a challenge to this PR's system, although I love it more.

**Comment by byronsharman** [comment]
> Also, some snaps need to be installed with --classic.

Will it be OK to install all Snap apps with `--classic`, or will the two have to be separated in the code?

**Comment by joshlangley** [comment]
Also, I know that chromium should technically be installed from snap, but for some reason there is a bug where the GTK3 support kicks in for more themes when installed via apt, which now installs the snap.

**Comment by joshlangley** [comment]
It's a very, very bad idea to install all snaps as classic, as A) snaps under strict confinement will not install as classic and B) the prized possession of snappy is it's sandboxing, as it is very secure and makes things cleaner in general. When installed in `--classic`, the sandbox is broken, and the app is given free roam. I'd much rather keep things secure and not just use the quick and dirty hack if you know what I mean. ;)

**Comment by joshlangley** [comment]
Too add complexities to this system, some apt package names are changing in newer Ubuntu systems in order to simplify things. I'm all for this, but ironically, it makes life more complex in the short term. For instance:
`libaa-bin` has become just `libaa`
`wine-stable` has become simply `wine`
there are some more, but I can't recall them right now.

Don't worry, I'll help with this all that I can.

**Comment by byronsharman** [comment]
It won't be hard to make it work; it will just take a little time.

**Comment by joshlangley** [comment]
If there's any way, however, I think I'd rather take an approach where the user can choose the source. There would, of course, be a sort of priority for each package, but changing the source would be as easy as a dropdown menu. I would also want to add support for apt 'minimal' packages and snap 'channels'.

Anyway, I know this all adds fathoms of complexity, but I do want to start off right instead of needing to rewrite the backend later in order to accommodate this. Sure, maybe we only start with stable, full packages from certain sources, but I want the base to be there.

**Comment by byronsharman** [comment]
Shouldn't Steamengine Locomotive be moved to the "Toys" section?

Also, I can't find `flashplayerstuff` at https://packages.ubuntu.com, nor `openoffice-desktopeditors` or `googletools-desktop` at https://snapcraft.io/store. Would you mind confirming that those are right?

Additionally, I can't find a clear reasoning behind the order of apps in each category. Should those be alphabetical for consistency?

**Comment by joshlangley** [comment]
`flashplayerstuff` was more of a note that there are a handful of commands needed to fully implement this. Sorry about that.
```
sudo apt install adobe-flashplugin adobe-flash-properties-gtk
sudo apt install browser-plugin-freshplayer-pepperflash
```
Also, I keep forgetting that it's actually `onlyoffice-desktopeditors`, not `openoffice-desktopeditors`. I don't know why it is that I struggle with this so much. I'm also getting pretty mad at the developer of `googletools-desktop` because it's such a cool tool, and I love it, but the developer keeps putting it up and taking it down. I don't know why. Either way, I'm fed up with it and would like to just remove it from Ignition.

**Comment by joshlangley** [comment]
Another update: I want to make "GStreamer Codecs" become "Media Codecs" and add the following to it:
```
sudo add-apt-repository multiverse
sudo apt install ubuntu-restricted-extras
```
See the README.md file. I have some updates to the whole general thing. I think this would make a good .sh install.

**Comment by byronsharman** [comment]
Would it be possible to install the Flash player packages with a single line like 

```
sudo apt install adobe-flashplugin adobe-flash-properties-gtk browser-plugin-freshplayer-pepperflash
```

or does that not work?

**Comment by joshlangley** [comment]
That _should_ work.

**Comment by byronsharman** [comment]
If it isn't certain, it might be best for me to add a `custom` option for packages that do not use apt or snap. That way I could also accommodate packages that require things such as adding repositories, e.g. "Media Codecs."

**Comment by joshlangley** [comment]
I was thinking that custom would just be done with .sh files. That would make it pretty easy.

**Comment by byronsharman** [comment]
Oh, that's a great idea! How come I hadn't thought of it before? :sweat_smile:

**Pull request closed without merging**
